name: Ensure Clean Notebook Metadata

on:
  push:
    paths:
      - '/'
  pull_request:
    branches:
      - master

jobs:
  clean-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Notebooks for clean metadata
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
        with:
          disable-checks: execution_count
